services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - /app/venv # Exclude virtual environment from volume mount
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vibemeter
      - ENVIRONMENT=development
      - HOST=0.0.0.0
    depends_on:
      - db
    # Command is now handled by the start.sh script in the Dockerfile

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vibemeter
    ports:
      - "5432:5432"

volumes:
  postgres_data:
